kserve-crd: {}

kserve:
  kserve:
    controller:
      deploymentMode: RawDeployment
      gateway:
        domain: oremuslabs.app
        domainTemplate: "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}"
        urlScheme: https
        disableIstioVirtualHost: true
        disableIngressCreation: true
        additionalIngressDomains: []
        localGateway:
          gateway: knative-serving/knative-local-gateway
          gatewayService: knative-local-gateway.istio-system.svc.cluster.local
          knativeGatewayService: ""
        ingressGateway:
          enableGatewayApi: true
          kserveGateway: traefik/traefik-public
          createGateway: false
          gateway: knative-serving/knative-ingress-gateway
          className: traefik
