{{- $secret := .Values.githubTokenSecret }}
{{- if and $secret $secret.create $secret.onepassword.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secret.name | default (printf "%s-github-token" (include "sourcebot.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/tracking-id: {{ printf "%s:%s/%s" .Release.Name "OnePasswordItem" ($secret.name | default (printf "%s-github-token" (include "sourcebot.fullname" .))) }}
spec:
  itemPath: {{ $secret.onepassword.itemPath | quote }}
{{- end }}
