{{- $secret := .Values.gitSync.apiSecret }}
{{- if and $secret $secret.name $secret.onepassword.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/tracking-id: {{ printf "%s:%s/%s" .Release.Name "OnePasswordItem" $secret.name }}
spec:
  itemPath: {{ $secret.onepassword.itemPath | quote }}
{{- end }}
