{{- $secret := .Values.githubTokenSecret | default dict }}
{{- if and $secret.create $secret.onepassword.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secret.name | default (printf "%s-github-token" (include "n8n.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/tracking-id: {{ printf "%s:%s/%s" .Release.Name "OnePasswordItem" (default (printf "%s-github-token" (include "n8n.fullname" .)) $secret.name) }}
spec:
  itemPath: {{ $secret.onepassword.itemPath | quote }}
{{- end }}
