apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firecrawl.fullname" . }}-playwright
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: playwright
      {{- include "firecrawl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: playwright
        {{- include "firecrawl.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "firecrawl.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ .name | default . }}
        {{- end }}
      {{- end }}
      containers:
        - name: playwright
          image: {{ .Values.playwright.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
              name: http
          resources:
            {{- toYaml .Values.playwright.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "firecrawl.fullname" . }}-playwright
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: playwright
    {{- include "firecrawl.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: http
