apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firecrawl.fullname" . }}-redis
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      {{- include "firecrawl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        {{- include "firecrawl.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "firecrawl.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ .name | default . }}
        {{- end }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          args:
            - "redis-server"
            - "--bind"
            - "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "firecrawl.fullname" . }}-redis
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: redis
    {{- include "firecrawl.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
