apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oremuslabs-app-wildcard
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: oremuslabs-app-wildcard-tls
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
  commonName: "*.oremuslabs.app"
  dnsNames:
    - "*.oremuslabs.app"
    - oremuslabs.app
