apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: open-webui
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.websocketPathPrefix }}`)
    {{- if .Values.ingress.websocketRoutePriority }}
    priority: {{ .Values.ingress.websocketRoutePriority }}
    {{- end }}
    {{- if .Values.ingress.websocketStripPrefix }}
    middlewares:
    - name: {{ printf "%s-ws-strip" .Release.Name }}
      namespace: {{ .Release.Namespace }}
    {{- end }}
    services:
    - name: {{ .Release.Name }}
      port: 80
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    {{- if .Values.ingress.middleware.enabled }}
    middlewares:
    - name: {{ .Values.ingress.middleware.name }}
      namespace: {{ .Values.ingress.middleware.namespace }}
    {{- end }}
    services:
    - name: {{ .Release.Name }}
      port: 80
  tls:
    secretName: {{ .Values.ingress.tlsSecret }}
