apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: open-webui
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    middlewares:
    - name: {{ .Values.ingress.middleware.name }}
      namespace: {{ .Values.ingress.middleware.namespace }}
    services:
    - name: {{ .Release.Name }}
      port: 8080
  tls:
    secretName: {{ .Values.ingress.tlsSecret }}
