{{- if .Values.oidcSecret.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.oidcSecret.name }}
  namespace: {{ include "open-webui.namespace" . }}
spec:
  itemPath: {{ .Values.oidcSecret.itemPath | quote }}
{{- end }}
