{{- $secrets := dict "postgres" .Values.postgres.credentialsSecret "dburl" .Values.postgres.urlSecret }}
{{- range $key, $secret := $secrets }}
  {{- if and $secret $secret.create $secret.onepassword.itemPath }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secret.name | default (printf "%s-%s" (include "coder-wrapper.fullname" $) $key) }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/tracking-id: {{ printf "%s:%s/%s" $.Release.Name "OnePasswordItem" ($secret.name | default (printf "%s-%s" (include "coder-wrapper.fullname" $) $key)) }}
spec:
  itemPath: {{ $secret.onepassword.itemPath | quote }}
  {{- end }}
{{- end }}
