apiVersion: v1
kind: Service
metadata:
  name: smb-server
  namespace: smb
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.51
  selector:
    app: smb-server
  ports:
  - name: smb
    port: 445
    targetPort: 445
  - name: netbios
    port: 139
    targetPort: 139
