apiVersion: v2
name: authoritative-coredns
description: CoreDNS instance serving Oremus Labs zones
type: application
version: 0.1.0
dependencies:
  - name: coredns
    version: 1.45.0
    repository: https://coredns.github.io/helm
