apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass-minio.yaml
  - storageclass-smb.yaml
  - node-tag-sa.yaml
  - node-tag-clusterrole.yaml
  - node-tag-clusterrolebinding.yaml
  - node-tag-job.yaml
