{{- if and .Values.huggingface.enabled .Values.huggingface.onepassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.huggingface.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "{{ .Values.huggingface.onepassword.itemPath }}"
{{- end }}
