apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: hf-token
  namespace: {{ .Values.namespace }}
spec:
  itemPath: "vaults/fekk46izlezqrgocthhcn4xwp4/items/x7v2wiq2m7xwf6qguv4a3xxhb4"
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-token
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  token: op://fekk46izlezqrgocthhcn4xwp4/x7v2wiq2m7xwf6qguv4a3xxhb4/HUGGING_FACE_HUB_TOKEN
