{{- $hosts := list }}
{{- if .Values.route.hosts }}
  {{- $hosts = .Values.route.hosts }}
{{- else if .Values.route.host }}
  {{- $hosts = list .Values.route.host }}
{{- end }}
{{- if gt (len $hosts) 0 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-manager
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.route.ingressClass | default "traefik" | quote }}
spec:
  {{- if .Values.route.tlsSecret }}
  tls:
    - hosts:
        {{- range $hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.route.tlsSecret | quote }}
  {{- end }}
  rules:
    {{- range $hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: model-manager
                port:
                  number: 80
    {{- end }}
{{- end }}
