apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.onepassword.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  itemPath: "{{ .Values.onepassword.itemPath }}"
