apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-manager
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: model-manager
subjects:
  - kind: ServiceAccount
    name: model-manager
    namespace: {{ .Values.namespace }}
