apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: model-manager
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
