{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: model-manager
    app.kubernetes.io/component: redis
spec:
  selector:
    app.kubernetes.io/name: model-manager
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
{{- end }}
