apiVersion: v1
kind: Service
metadata:
  name: model-manager-stable
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: model-manager
    app.kubernetes.io/part-of: ai-model-manager
spec:
  type: ClusterIP
  selector:
    serving.knative.dev/service: model-manager
  ports:
    - name: http
      port: 80
      targetPort: 8012
    - name: https
      port: 443
      targetPort: 8112