apiVersion: v1
kind: Service
metadata:
  name: model-manager
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: model-manager
    app.kubernetes.io/part-of: ai-model-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: model-manager
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
