apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: searxng-secret
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/fekk46izlezqrgocthhcn4xwp4/items/fw5a46ctcn5ygcaw4ehckh226i"
