apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    middlewares:
    - name: oauth2proxy-forwardauth
      namespace: traefik
    services:
    - name: homepage
      port: 3000
  {{- if .Values.ingress.tlsSecret }}
  tls:
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
