apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: router-upstream
  namespace: traefik
spec:
  weighted:
    services:
    - name: router-lb
      kind: TraefikService
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: router-lb
  namespace: traefik
spec:
  loadBalancer:
    servers:
    - url: {{ .Values.router.url | quote }}
    passHostHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: router
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.router.host }}`)
    services:
    - name: router-upstream
      kind: TraefikService
  tls:
    secretName: {{ .Values.router.tlsSecret }}
