apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator.tigera.io_apiservers_crd.yaml
  - operator.tigera.io_imagesets_crd.yaml
  - operator.tigera.io_installations_crd.yaml
  - operator.tigera.io_tigerastatuses_crd.yaml
