apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: traefik
  annotations:
    traefik.io/ingress-controller: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`argocd.oremuslabs.app`)
    services:
    - name: argo-cd-argocd-server
      namespace: argocd
      port: 80
  tls:
    secretName: oremuslabs-app-wildcard-tls
