apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: traefik
  annotations:
    traefik.io/ingress-controller: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`headlamp.oremuslabs.app`)
    services:
    - name: headlamp
      namespace: headlamp
      port: 80
  tls:
    secretName: oremuslabs-app-wildcard-tls
