apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - longhorn.yaml
  - op-connect.yaml
  - minio-api.yaml
  - minio-console.yaml
  - headlamp.yaml
  - traefik-dashboard.yaml
