apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: traefik
  annotations:
    traefik.io/ingress-controller: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`longhorn.oremuslabs.app`)
    services:
    - name: longhorn-frontend
      namespace: longhorn-system
      port: 80
  tls:
    secretName: oremuslabs-app-wildcard-tls
