apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-api
  namespace: traefik
  annotations:
    traefik.io/ingress-controller: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`s3.oremuslabs.app`)
    services:
    - name: minio
      namespace: minio
      port: 9000
  tls:
    secretName: oremuslabs-app-wildcard-tls
