apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: traefik
  annotations:
    traefik.io/ingress-controller: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`minio.oremuslabs.app`)
    middlewares:
    - name: oauth2proxy-forwardauth
      namespace: traefik
    services:
    - name: minio-console
      namespace: minio
      port: 9001
  tls:
    secretName: oremuslabs-app-wildcard-tls
