apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2proxy-forwardauth
  namespace: traefik
spec:
  forwardAuth:
    address: http://oauth2-proxy.traefik.svc.cluster.local:4180/oauth2/auth_or_start
    trustForwardHeader: true
    authResponseHeaders:
      - Authorization
      - X-Auth-Request-Access-Token
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Groups
      - X-Auth-Request-Redirect
      - X-Auth-Request-Username
      - Set-Cookie
