apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: op-connect
  namespace: traefik
  annotations:
    traefik.io/ingress-controller: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`op.oremuslabs.app`)
    services:
    - name: onepassword-connect
      namespace: 1password
      port: 8080
  tls:
    secretName: oremuslabs-app-wildcard-tls
