namespace: gpt-researcher
replicaCount: 1

image:
  repository: ghcr.io/oremus-labs/gpt-researcher-nextjs
  tag: nextjs-v1
  pullPolicy: IfNotPresent

service:
  port: 3000
  type: ClusterIP

ingress:
  host: researcher.oremuslabs.app
  tlsSecret: oremuslabs-app-wildcard-tls
  entryPoints:
    - websecure

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
