{{- range .Values.proxies }}
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: {{ .name }}-upstream
  namespace: traefik
spec:
  weighted:
    services:
    - name: {{ .name }}-lb
      kind: TraefikService
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: {{ .name }}-lb
  namespace: traefik
spec:
  loadBalancer:
    passHostHeader: true
    servers:
    - url: {{ .url | quote }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .host }}`)
    services:
    - name: {{ .name }}-upstream
      kind: TraefikService
  tls:
    secretName: {{ .tlsSecret }}
---
{{- end }}
