{{- range .Values.proxies }}
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: {{ .name }}-proxy
  namespace: traefik
spec:
  loadBalancer:
    passHostHeader: true
    servers:
      - url: {{ .url | quote }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}-proxy
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .host }}`)
    services:
    - name: {{ .name }}-proxy
      namespace: traefik
      kind: TraefikService
  tls:
    secretName: {{ .tlsSecret }}
---
{{- end }}
