{{- range .Values.proxies }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-upstream
  namespace: traefik
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}-upstream
  namespace: traefik
subsets:
  - addresses:
      - ip: {{ .url | trimPrefix "http://" | trimPrefix "https://" | trimSuffix "/" }}
    ports:
      - name: http
        port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .host }}`)
    services:
    - name: {{ .name }}-upstream
      namespace: traefik
      port: 80
  tls:
    secretName: {{ .tlsSecret }}
---
{{- end }}
