apiVersion: v1
kind: Service
metadata:
  name: {{ include "deep-research-postgres.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "deep-research-postgres.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
  selector:
    app.kubernetes.io/name: {{ include "deep-research-postgres.fullname" . }}
