apiVersion: v2
name: argocd
description: Wrapper chart that pins upstream argo-cd Helm values for Oremus Labs
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 9.1.1
    repository: https://argoproj.github.io/argo-helm
