argo-cd:
  global:
    domain: argocd.oremuslabs.app
  configs:
    cm:
      url: https://argocd.oremuslabs.app
    params:
      applicationsetcontroller.enableLeaderElection: "true"
  server:
    service:
      type: LoadBalancer
      annotations:
        kube-vip.io/loadbalancerIPs: "10.10.10.51"
    ingress:
      enabled: false
  controller:
    enableStatefulSet: false
  redis:
    enabled: true
  dex:
    enabled: false
