argo-cd:
  global:
    domain: argocd.oremuslabs.app
  configs:
    cm:
      url: https://argocd.oremuslabs.app
    params:
      applicationsetcontroller.enableLeaderElection: "true"
  server:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: first-pool
    ingress:
      enabled: false
  controller:
    enableStatefulSet: false
  redis:
    enabled: true
  dex:
    enabled: false
