apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpt-researcher.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gpt-researcher.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "gpt-researcher.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
