apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oremus-labs-platform-configs
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: cert-manager-resources
        namespace: cert-manager
        project: platform
        path: apps/platform/cert-manager
        targetRevision: main
        syncWave: "1"
      - name: traefik-routes
        namespace: traefik
        project: platform
        path: apps/platform/traefik/routes
        targetRevision: main
        syncWave: "1"
      - name: metallb-resources
        namespace: metallb-system
        project: platform
        path: apps/platform/metallb/resources
        targetRevision: main
        syncWave: "0"
      - name: argocd-resources
        namespace: argocd
        project: platform
        path: apps/platform/argocd/resources
        targetRevision: main
        syncWave: "1"
      - name: minio-resources
        namespace: minio
        project: platform
        path: apps/platform/minio/resources
        targetRevision: main
        syncWave: "1"
      - name: headlamp-resources
        namespace: headlamp
        project: platform
        path: apps/platform/headlamp/resources
        targetRevision: main
        syncWave: "1"
      - name: smb-resources
        namespace: smb
        project: platform
        path: apps/platform/smb/resources
        targetRevision: main
        syncWave: "1"
      - name: rbac-resources
        namespace: kube-system
        project: platform
        path: apps/platform/rbac/resources
        targetRevision: main
        syncWave: "1"
      - name: longhorn-resources
        namespace: longhorn-system
        project: platform
        path: apps/platform/longhorn/resources
        targetRevision: main
        syncWave: "1"
      - name: local-pv-resources
        namespace: kube-system
        project: platform
        path: apps/platform/local-pv/resources
        targetRevision: main
        syncWave: "1"
      - name: coredns-resources
        namespace: kube-system
        project: platform
        path: apps/platform/coredns/resources
        targetRevision: main
        syncWave: "1"
  template:
    metadata:
      name: platform-{{name}}
      labels:
        oremus-labs.com/tier: platform
      annotations:
        argocd.argoproj.io/sync-wave: '{{default "0" syncWave}}'
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/Oremus-Labs/ol-kubernetes-cluster.git
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
