apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "triton-vllm.fullname" . }}-config
  labels:
    {{- include "triton-vllm.labels" . | nindent 4 }}
data:
  TRITONSERVER_ARGS: {{ .Values.env.TRITONSERVER_ARGS | quote }}
