apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triton-vllm.fullname" . }}
  labels:
    {{- include "triton-vllm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "triton-vllm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "triton-vllm.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: triton-vllm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TRITONSERVER_ARGS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "triton-vllm.fullname" . }}-config
                  key: TRITONSERVER_ARGS
          envFrom:
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
          volumeMounts:
            - name: model-repo
              mountPath: {{ .Values.modelRepo.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: model-repo
          persistentVolumeClaim:
            claimName: {{ include "triton-vllm.fullname" . }}-modelrepo-pvc
