{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "triton-vllm.fullname" . }}
  labels:
    {{- include "triton-vllm.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.pathType | quote }}
            backend:
              service:
                name: {{ include "triton-vllm.fullname" . }}
                port:
                  number: {{ .Values.service.httpPort }}
{{- end }}
