namespace: ai

image:
  repository: ghcr.io/oremus-labs/ol-model-manager-ui
  tag: "0.3.0"
  pullPolicy: Always

replicaCount: 1

service:
  port: 3000

ingress:
  host: model-manager.oremuslabs.app
  tlsSecret: oremuslabs-app-wildcard-tls
  middleware: oauth2proxy-forwardauth-lite

env:
  apiBaseUrl: http://model-manager.ai.svc.cluster.local

apiToken:
  enabled: true
  secretName: model-manager-api-token
  secretKey: token

resources: {}
