apiVersion: v1
kind: Service
metadata:
  name: {{ include "deep-research-embedding.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "deep-research-embedding.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "deep-research-embedding.fullname" . }}
