{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pv.name }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storage.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.className }}
  local:
    path: {{ .Values.storage.pv.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.node.hostname }}
{{- end }}
