apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/tracking-id: workloads-qwen-vllm:/PersistentVolumeClaim:{{ .Values.namespace }}/{{ .Values.storage.pvc.name }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.className }}
  volumeName: {{ .Values.storage.pv.name }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
