{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.className }}
  volumeName: {{ .Values.storage.pv.name }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
