{{- if .Values.rbac.enabled }}
{{- $server := index .Values "kubernetes-mcp-server" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.bindingName }}
  labels:
    app.kubernetes.io/name: kubernetes-mcp-server
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.existingClusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ required "serviceAccount name is required" $server.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
