{{- $server := index .Values "kubernetes-mcp-server" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "serviceAccount name is required" $server.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kubernetes-mcp-server
    app.kubernetes.io/instance: {{ .Release.Name }}
