apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform.yaml
  - projects/workloads.yaml
  - appsets/platform-core.yaml
  - appsets/platform-kustomize.yaml
  - appsets/workloads.yaml
