oauth2-proxy:
  replicaCount: 1
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.6.0
  service:
    type: ClusterIP
    portNumber: 4180
  ingress:
    enabled: false
  config:
    provider: oidc
    oidcIssuerUrl: ""
    redirectUrl: ""
    emailDomains:
      - "*"
    upstreams:
      - file:///dev/null
    cookie:
      secure: true
      samesite: lax
  metrics:
    enabled: false
  extraEnvFrom: []
  extraArgs: {}
  resources: {}

traefik:
  host: ""
  tlsSecret: ""

onepassword:
  itemPath: ""
