namespace: ai

gatewayApi:
  hosts:
    - ai.oremuslabs.app
  parentRefs:
    - name: traefik-public
      namespace: traefik
      sectionName: websecure
  backendService:
    name: active-llm-predictor
    port: 80
  modelManagerService:
    name: model-manager
    port: 80
