{{- if and .Values.patSecret.create .Values.patSecret.onepassword.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.patSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: {{ .Values.patSecret.onepassword.itemPath | quote }}
{{- end }}
