fullnameOverride: ""

image:
  repository: qdrant/qdrant
  tag: v1.11.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  apiPort: 6333
  grpcPort: 6334

persistence:
  enabled: true
  size: 300Gi
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 8Gi

nodeSelector:
  kubernetes.io/hostname: pluto

tolerations: []
affinity: {}

qdrantSecret:
  create: true
  name: deep-research-qdrant
  onepassword:
    itemPath: "vaults/fekk46izlezqrgocthhcn4xwp4/items/kqtkzlisbd7n7ldy24ptpzx4gu"
